load("@rules_java//java:defs.bzl", "java_library", "java_test")

java_library(
    name = "krabka-streams-columnar",
    srcs = glob(["src/main/java/**/*.java"]),
    javacopts = ["--release", "17"],
    visibility = ["//visibility:public"],
    deps = [
        "//krabka-streams",
        "@krabka_streams_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@krabka_streams_maven//:org_apache_arrow_arrow_memory_core",
        "@krabka_streams_maven//:org_apache_arrow_arrow_vector",
    ],
    exports = [
        "//krabka-streams",
        "@krabka_streams_maven//:org_apache_arrow_arrow_memory_core",
        "@krabka_streams_maven//:org_apache_arrow_arrow_vector",
    ],
    runtime_deps = ["@krabka_streams_maven//:org_apache_arrow_arrow_memory_netty"],
)

java_test(
    name = "tests",
    srcs = glob(["src/test/java/**/*.java"]),
    args = ["execute", "--select-package=io.krabka.streams.columnar", "--fail-if-no-tests"],
    javacopts = ["--release", "17"],
    jvm_flags = ["--add-opens=java.base/java.nio=ALL-UNNAMED"],
    main_class = "org.junit.platform.console.ConsoleLauncher",
    use_testrunner = False,
    deps = [
        ":krabka-streams-columnar",
        "@krabka_streams_maven//:org_junit_platform_junit_platform_console_standalone",
    ],
)
