name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [17, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - run: >-
          bazel test //...
          --config=remote
          --remote_header=x-buildbuddy-api-key=${BUILDBUDDY_API_KEY}
          --java_runtime_version=remotejdk_${{ matrix.java }}
          --tool_java_runtime_version=remotejdk_${{ matrix.java }}
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
